### ISSUE TITLE
ElasticSearch 5.0 Compatibility Issues?

### ISSUE THREAD

**Issue by rmclean45** [WedjaaOpen/ElasticJasper#10]
This is a bit speculative but I'm running into transport errors when trying to communicate with ElasticJasper 6.2.2 and my 5.1.1 instance of ES. ES throws the following errors: 

> [2017-02-03T09:41:47,883][WARN ][o.e.t.n.Netty4Transport  ] [CVOqk_g] exception caught on transport layer [[id: 0x4fdc82d6, L:/172.17.
> 0.2:9300 - R:/172.17.0.1:57676]], closing connection
> java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]
>         at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1236) ~[elasticsearch-5.1.1.jar:5.1.1]
>         at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport
> -netty4-5.1.1.jar:5.1.1]

I'm a bit new to ES however the errors correlate to the times I'm trying to connect with EJ. If this is a compatibility issue, are there plans to work with 5.0?

**Comment by ThomasFlanaghan** [comment]
Hi,

Running into the same issues here. did you find a resolution?

**Comment by rmclean45** [comment]
Nope, sorry. We just left it be. It's a pity. I asked Jasper support for any solutions and they didn't know what Elasticsearch was so that was a massive dead-end.

I hope you find some success!

**Comment by Wedjaa** [comment]
We need to upgrade the libraries for the client to 5.0 and then do some regression testing.

**Comment by ThomasFlanaghan** [comment]
Hi,

Do you know exactly what libraries need upgrading / know how to find out?

Thanks.
