### ISSUE TITLE
Cannot create Data Adapter

### ISSUE THREAD

**Issue by scrawfor** [WedjaaOpen/ElasticJasper#8]
Running JasperStudio 6.3.0.

I have entered my hostname, port and cluster name.  I validated the values from elasticsearch.yml. I also telneted into the box to ensure the port was open.

I get this error:

```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{xx.xx.xx.xxx}{c3duanalytics1/xx.xx.xx.xxx:9300}]]
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
    at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
    at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
    at net.wedjaa.elasticparser.ESSearch.executeSearch(ESSearch.java:509)
    at net.wedjaa.elasticparser.ESSearch.executeSearch(ESSearch.java:524)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:555)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:568)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:621)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:631)
    at net.wedjaa.elasticparser.ESSearch.test(ESSearch.java:638)
    at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterService.test(ESAdapterService.java:115)
    at com.jaspersoft.studio.data.wizard.AbstractDataAdapterWizard$3.runOperations(AbstractDataAdapterWizard.java:162)
    at com.jaspersoft.studio.utils.jobs.CheckedRunnableWithProgress$1.run(CheckedRunnableWithProgress.java:59)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Wedjaa** [comment]
What port did you try? 9200 is the HTTP transport, we are using 9300. Could you check this port is also open?

**Comment by scrawfor** [comment]
I tried both, and made sure both ports were open.

**Comment by cs-chaturbhuj-singh** [comment]
What version of elasticsearch are you running. I am pretty sure it is not 2.x. I also get this error and the reason being unsupported version. I was running version 1.5.2 of elasticsearch. The plugin supports only 2.x version
